### ISSUE TITLE
jQuery.on() examples appear incorrect

### ISSUE THREAD

**Issue by WanderingZombie** [qTip2/qTip2#552]
In the documentation, the following is shown as how to use event delegation, but it doesn't work with jQuery 1.9.1

``` php
$(document).on('.selector', 'mouseover', function(event) {...});
```

Swap the event and selector arguments and it works like a dream

``` php
$(document).on('mouseover', '.selector', function(event) {...});
```

Additionally, I receive the error "TypeError: this.removeAttribute is not a function" with the example code, so

``` php
.each(function(i) {
    $.attr(this, 'oldtitle', $.attr(this, 'title'));
    this.removeAttribute('title');
});
```

needs to be something like

``` php
.each(function(i) {
    var $$ = $(this);
    $$.attr('oldtitle', $$.attr('title')).attr('title', '');
});
```
