### ISSUE TITLE
a.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by achwell** [qTip2/qTip2#184]
I am using jQuery 1.6.2 and qTip2 nightly-b897d54beb5770addfe13e3bc78ebe131309093683.
When using FireFox 5, I got the following javascript error:

a.compareDocumentPosition is not a function

Works fine with chrome 12.0.742.112, IE7, IE8, Opera 11 and safari 5.0.5
