### ISSUE TITLE
$('#myelement').qtip is not a function

### ISSUE THREAD

**Issue by ringemup** [qTip2/qTip2#289]
In Firefox 8.  Works fine using a nightly dated "Thu Dec 15 11:17:28.0000000000 2011" in but broken in ceba974.
